### ISSUE TITLE
Integrate API 

### ISSUE THREAD

**Issue by sameeerkashyap** [Sameerkash/covidapp#2]
Create a repository class to handle and Integrate API requests and responses given in the documentation.
Test APIs endpoints in a suitable.
Create Model classes.

**Comment by 98lenvi** [comment]
I'd like to work on this! @Sameerkash

**Comment by sameeerkashyap** [comment]
Sure! Thing but the project is blank yet. 
You can write methods to make API calls

**Comment by 98lenvi** [comment]
I'm missing javascript here :cry:
